
"use client";

import { GraduationCap, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50 pb-20">
      <header className="h-20 bg-white border-b flex items-center px-4 md:px-12">
        <Link className="flex items-center gap-2" href="/">
          <GraduationCap className="h-6 w-6 text-primary" />
          <span className="font-black tracking-tighter text-xl">StudyPilot AI</span>
        </Link>
        <Button variant="ghost" className="ml-auto font-bold gap-2" asChild>
          <Link href="/"><ArrowLeft className="h-4 w-4" /> Back to Home</Link>
        </Button>
      </header>

      <main className="max-w-3xl mx-auto mt-12 px-6 bg-white p-10 md:p-16 rounded-[2.5rem] shadow-sm">
        <h1 className="text-4xl font-black font-headline tracking-tight mb-8">Privacy Policy</h1>
        <p className="text-slate-400 font-bold mb-10 italic text-sm">Last Updated: July 2024</p>
        
        <div className="space-y-8 text-slate-600 leading-relaxed font-medium">
          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 uppercase tracking-widest text-[10px]">1. Information We Collect</h2>
            <p>We collect basic information such as your name, email address, and profile picture (if using Google Login) to create and manage your study account. We also store the notes you paste and the outputs generated to provide your study history.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 uppercase tracking-widest text-[10px]">2. How We Use Data</h2>
            <p>Your data is used to personalize your experience, track your study usage limits, and improve our AI prompt results for academic subjects. We do not sell your personal notes or contact information to third parties.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 uppercase tracking-widest text-[10px]">3. Payment Security</h2>
            <p>Payment processing is handled securely by Razorpay. StudyPilot AI does not store your credit card numbers, UPI PINs, or banking passwords on our servers.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-slate-900 uppercase tracking-widest text-[10px]">4. AI & Content</h2>
            <p>Content generated by our AI is for study assistance only. We use Google Gemini to process study material. Your data is processed in accordance with Google's AI safety and privacy guidelines.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
